# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 26f8be3e0096474d7e7acf284d86ec65c3e05f963bfc8a3df4abb3571a42f6568a744d57234c661f401580f31e427a0eefe410a8218fabb837eafe89faf2a910

test:
  secret_key_base: d3b27a7afe80175feea480565cb2035547f478faddb1aac93d34d17ef5a5f6b600dc5b7de459956760be0a72b7402a0adb616a266c71507a81b8a00b23282672

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
